## Welcome to Python!!
a knowledge sharing session

references:
* https://github.com/jakevdp/PythonDataScienceHandbook
* http://tdc-www.harvard.edu/Python.pdf
* http://pandas.pydata.org/pandas-docs/stable/10min.html
* http://twiecki.github.io/blog/2014/11/18/python-for-data-science/
* https://www.dataquest.io/blog/machine-learning-python/
* with additional insights from various learning experiences

## Course Outline

* Installation
* Navigating the notebook
    * importing libraries
    * getting help
    * SYNTAX - the indentation, code structure
    * data types & basic operations
    * logical Operators
    * variable assignment
    > possible break here
    * Basic data structures - List, Dicts, Tuples, Strings
    * Basic lambda functions
    * saving notebook into a script file
    
* Data Manipulation with Pandas
    * Introduction to numpy arrays
    * broadcasting, reshaping
    * operations on np arrays
    * Introduction to pandas
    * getting and reading data
    * writing data
    * DataFrame manipulation 
        * https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf
        * creating DataFrame
        * subsetting DataFrame (Masking, iloc, loc)
        * summarizing data (df.describe,np.sum(), df.head etc)
        * adding columns to DataFrame (assign, df method)
    * Merging DataFrames
    
* Introduction to Statistical Analysis and Machine Learning
    * correlation
    * Statistical tests
    * Linear regression
    * Intro to scikit functions
    
* Assignment
    











### Importing libraries
in python, we import libraries using the following commands

In [2]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd

In [1]:
#this is how we comment
#below is how we find help
pd?
#help(pd.DataFrame)


Object `pd` not found.


### Basic python syntax
* Indentation instead of traditional {curly_braces} 
* Use \ when we should go the next line prematurely
* in function and class definitions, a colon usually appears
* index begins in zero

In [79]:
x = [1,2,3,4,5] #example of a list
y = [1,1,1,1,1]
z = []

for i in range(0,len(x)):
    z.append(x[i]+y[i])
    print(z[i],'index: %.i' %i)



2 index: 0
3 index: 1
4 index: 2
5 index: 3
6 index: 4


In [82]:
def adder(x,y):
    """ This a docstring for
    this adder function"""
    z = [] #initialize z
    for i in range(0,len(x)):
        z.append(x[i]+y[i])
        print(z)    
    return z
    
adder(x,y)
        

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 5]
[2, 3, 4, 5, 6]


[2, 3, 4, 5, 6]

### Data types & basic operations


In [3]:
#integers
z = int(5/2)
print(z, type(z))

#float
pi = 3.141516
print(pi, type(pi))

txt = 'This is a string' #alternatively we can use ""
print(txt, type(txt))

#Complex Number
cmp = complex(3,7)
print(cmp, type(cmp))

2 <class 'int'>
3.141516 <class 'float'>
This is a string <class 'str'>
(3+7j) <class 'complex'>


In [4]:
a = 2+3 #addition
b = 3*5 #multiplication
c = 121/7 #division
d = 7%3 #modulo


In [12]:
for i in [a,b,c,d]:
    print(i)




5
15
17.285714285714285
1


### Logical Operators
in python, logical operators are words not symbols (and, or, not)

numerical comparisons are conventional

In [13]:
x = 5
y = 17
z = 9

In [19]:
print(x > y)
print(y < 5)
print(z == 9)
print(y != z)

False
False
True
True


In [20]:
(x < 8) or (y != 17) 

True

In [21]:
(x != 5) and (z > 9)

False

In [26]:
not( (x != 5) and (z > 9) )
#not gives the opposite

True

In [27]:
(x != 5) not (z > 9)

SyntaxError: invalid syntax (<ipython-input-27-7dfb3d79348d>, line 1)

### Variable Assignment
* In python, assingment create references not copies

In [83]:
x = 4 #assign 4 to x
y = x #assing x to y

In [87]:
x = 3 #change x to 3
y #print y

#note that y is changed too, y = x  did not create a copy of x to be assigned to y
#but why? :)
#try to search Garbage collection

3

In [88]:
# we can also do multiple assignments
x,y = 'this is x', 4
print(x)
print(y)

this is x
4


### Basic Data Structures
Lists, strings and tuples are ordered sequences of objects. Unlike strings that contain only characters, list and tuples can contain any type of objects. Lists and tuples are like arrays. Tuples like strings are immutables. Lists are mutables so they can be extended or reduced at will. Sets are mutable unordered sequence of unique elements whereas frozensets are immutable sets.


#### LISTS
* ordered sequence
* mutable
* can contain any type of objects

In [93]:
smpl = [1,2,3,4,5,6,7,8,91]
smpl
#Squares are defined by square brackets
#lists are mutable

[1, 2, 3, 4, 5, 6, 7, 8, 91]

In [94]:
smpl.pop(2) #here we pop the element at index 2, we can update a list!
smpl

[1, 2, 4, 5, 6, 7, 8, 91]

In [97]:
random = ['name', 100, True] #Lists can contain different types of object
random


['name', 100, True]

Problem 1: create a list of squared integers from 1 to 100

In [112]:

# sample of a list comprehension
#

#squared = [i**2 for i in range(0,100)]
#squared

#### TUPLES
* ordered sequence
* immutable
* can contain any type of objects

In [98]:
tupl = (1,2,3,4,5)
tupl

(1, 2, 3, 4, 5)

In [99]:
tupl.pop(3) #this will generate an error

AttributeError: 'tuple' object has no attribute 'pop'

#### STRINGS
* strings can be thought of as a list
* but they are immutable!

In [166]:
st = "Hello QBE!"
st[8]

'E'

### Indexing and Slicing
most of the time we need to index/filter our data

In [122]:
t = ["abc", 1 , np.exp(1), [100,8,4]]



**Problem: How do we get the value 8?**

In [123]:
# indexing by array notation
t[0]

4
3


In [130]:
# try negative!
t[-1]

#what's the difference?

[100, 8, 4]

In [124]:
#from index 1 up to before index 4
t[1:4]

[1, 2.7182818284590451, [100, 8, 4]]

In [126]:
#t[3][2]

In [138]:
#indexing by [start:stop:step]
num = [x for x in range(1,21)]
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [146]:
index1 = num[0:18:3]
index1


[1, 4, 7, 10, 13, 16]

**Question how can we reverse this list?**

### The 'in', '+', '*' operators

In [149]:
# in
#Say for example, we want to check if an element is in a list
a_list = [i**3 for i in range(0,100)]

In [151]:
729 in a_list

True

In [157]:
# +
#the + operatrs for lists is for concatenation
zoo = ['tiger', 'rooster', 'pig']
add_animal = ['snake', 'kangaroo']
current = zoo + add_animal


In [155]:
# *
#the * repeats the original content
"--Hello Manila "*3

'--Hello Manila --Hello Manila --Hello Manila '

**What if we want to replace a contents of a list?**

In [158]:
current

['tiger', 'rooster', 'pig', 'snake', 'kangaroo']

In [161]:
current[1] = 'monkey'

In [162]:
current

['tiger', 'monkey', 'pig', 'snake', 'kangaroo']

**I want to add catterpillar, how can I do it?**

In [164]:
current.append('catterpillar')
current

['tiger', 'monkey', 'pig', 'snake', 'kangaroo', 'catterpillar']

### DICTS (*dictionaries*)
dictionaries are set of key-value pairs, i.e a mapping
* objects of different types are ok
* keys : any immutable type
* values: anything
* items are key-value pairs
* defined by {curly braces}
* indexed by keys

In [168]:
d = {'tp1': 100, 'tp2': 200, 'tp3': 500, 'QBE': 4500}
d

{'QBE': 4500, 'tp1': 100, 'tp2': 200, 'tp3': 500}

**How can we build a mapping?**

In [177]:
person = ('A', 'B', 'C', 'D', 'E')
password = ('1234' , 'erZe', 'afsd', '1wh32')

In [185]:
my_dict = {} #initialize dict
for k,v in zip(person,password):
    my_dict[k] = v


In [186]:
my_dict
#what do you notice

{'A': '1234', 'B': 'erZe', 'C': 'afsd', 'D': '1wh32'}

In [189]:
#notice that the values are printed in no particular order
my_dict.keys()



dict_keys(['C', 'A', 'B', 'D'])

In [190]:
my_dict.values()

dict_values(['afsd', '1234', 'erZe', '1wh32'])

In [191]:
my_dict.items()

dict_items([('C', 'afsd'), ('A', '1234'), ('B', 'erZe'), ('D', '1wh32')])

In [193]:
#Indexing dicts
#dicts are indexed with keys
my_dict['F']
#notice the error! it's "KeyError" hahaha

KeyError: 'F'

### Lambda Functions
"a function has no name"
* lambda : arguments expression

In [196]:
#Lambda functions are anonymous functions, used only on the line they are called
def mult_list(x):
    for i in x:
        i*=i
    return(i)

In [197]:
s = [1,2,3,4,5,6]
result = mult_list(s)

36

In [205]:
#translate the above using a lambda function
result = lambda x: (x*2) ,s
result

(<function __main__.<lambda>>, [1, 2, 3, 4, 5, 6])

### Using If - Else 

In [212]:
def is_larger(x,num):
    if x > num:
        print('your fave number is larger than ', num)
    elif x < num:
        print('uhhhm this is lesser than your favorite', x)
    else:
        print('Just equal')

In [213]:
x = input("enter your favorite number: ")
num = input("Enter a random number: ")
is_larger(x,num)

enter your favorite number: 23
Enter a random number: 1
your fave number is larger than  1


**Now we want to save this file**

# Data Manipulation With Pandas
> we'll discuss some preliminaries

## Numpy Arrays
building blocks of Pandas and some more advanced libraries like tesorflow
> **So what's a numpy array?**
>> Cotains values of a single type, to see full list of available dtypes see: http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb


In [5]:
import numpy as np

n = np.array([12,3,4,5,6,7,8], dtype = 'float64')
n

#similar to a list

array([ 12.,   3.,   4.,   5.,   6.,   7.,   8.])

In [4]:
n.dtype

dtype('float64')

In [12]:
#numpy arrays can also be multidimensional arrays
np.random.seed(2)

x = np.random.randint(20, size = (3,4,5))
print(x.shape) #.ndim, .size
x

(3, 4, 5)


array([[[ 8, 15, 13,  8, 11],
        [18, 11,  8,  7,  2],
        [17, 11, 15,  5,  7],
        [ 3,  6,  4, 10, 11]],

       [[19,  7,  6, 10,  1],
        [ 3,  5,  4, 14,  6],
        [19,  2, 16, 14, 12],
        [18,  4, 15, 17,  7]],

       [[14,  8, 18, 13, 15],
        [ 9, 13,  8, 17,  9],
        [ 9, 14, 19,  0, 11],
        [ 0, 18,  8, 12, 10]]])

In [13]:
#indexing numpy arrays:
x[0]

array([[ 8, 15, 13,  8, 11],
       [18, 11,  8,  7,  2],
       [17, 11, 15,  5,  7],
       [ 3,  6,  4, 10, 11]])

In [19]:
x[2,3]

array([ 0, 18,  8, 12, 10])

In [18]:
x[:2,:3,3] #we can also subset using : operator

array([[ 8,  7,  5],
       [10, 14, 14]])

not that in lists, slicing are returned as copies, in np arrays they are returned as views, meaning if you change the view, you will change the original

In [23]:
#Reshaping

x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x.reshape(3,3)

#sizes of the resultant reshaped must be equal to the original size

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Other numpy details are left as an assignment**

# Pandas
A powerful Data Analysis library for python

In [25]:
# Reading data with pandas
# we can read from different sources of data
HR_Data = pd.read_csv('https://www.kaggle.com/ludobenistant/hr-analytics/HR_comma_sep.csv')

HTTPError: HTTP Error 404: Not Found